# Generated by Django 2.2 on 2020-02-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='valor',
            field=models.FloatField(default=0),
        ),
    ]
