# Generated by Django 2.2 on 2020-02-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_servicos_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='valor',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
