# Generated by Django 2.2 on 2020-02-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20200221_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
