# Generated by Django 2.2 on 2020-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200221_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
