# Generated by Django 2.2 on 2020-02-21 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200221_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='valor',
        ),
    ]
