# Generated by Django 2.2 on 2020-02-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_remove_servicos_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='descricao',
        ),
    ]
