# Generated by Django 2.2 on 2020-02-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_servicos_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='valor',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
    ]
